# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  
jobs:
  job1-test:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v 
      
      
  job2_test_artifact:
    runs-on: ubuntu-latest
    needs: job1-test
    steps:
      - uses: actions/checkout@v3
      

      - run: echo hello > deployment_test
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: models
          
      - name: Create artifacts
        run: |
          mkdir -p test-artifact/test/artifact-A
  
    
  job_3_download_artifact:
    name: Download artifact
    needs: job2_test_artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact from job 1
        uses: actions/download-artifact@v3
        id: download
        with:
          name: my-artifact
          path: config
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: config
      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}
    
  job_4_download:
    runs-on: ubuntu-latest
    needs: job_3_download_artifact
    steps:
    - name: Checkout
      uses: actions/checkout@v3  
      
    # Test downloading a single artifact
    - name: Download artifact A
      uses: ./
      with:
        name: my-artifact
        path: utils
    
    
        
